### ISSUE TITLE
Update marketplace ver. to 4.26

### ISSUE THREAD

**Issue by AlexanderKyron** [PipeRift/FactionsExtension#11]
**Describe the feature requested**
When, how, what is the request about

The repo is compatible with 4.26, however, the Marketplace version is only marked as being compatible with 4.25. This is causing problems for a number of users as shown on the questions and reviews pages, however, has not at all been addressed and the questions have been left unanswered. 4.26 is going to be one of the last major versions of the engine, so it makes sense to support it as it's effectively one-and-done, don't have to worry about updating further until UE5.

**How does it help the user (you)?**
Ex. It reduces the amount of work I have to do

It reduces the barrier of entry for using the plugin to almost nothing, and makes people more likely to use it. 

**Is it related to a problem?**

A number of people who used this plugin in previous versions have left various reviews describing how the problem of not being updated and how it has impacted their workflow, made the plugin "useless", etc

At the very least, it would be appropriate to update those people on the fact that they need to go to the Github and get a copy of the source to use it, but it would be best to update the marketplace version instead of leaving a number of people's actual games that they need this plugin to keep working on stuck on an older version because they don't know.

**Comment by muit** [comment]
Support limited to 5.1 at the moment
