### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by rataman098** [PipeRift/FactionsExtension#12]
Hello! I just came across this addon, and the sole purpose is brilliant! (Being able to get factions to work without having to use C++ is amazing). The problem is, it doesn't seem to have been updated for a couple of years now. I really want to use it for my UE5 project, is there any chance of getting this addon revived?

**Comment by Starkium** [comment]
it's easy enough to convert. I plan on updating it to support two way faction testing as well

**Comment by muit** [comment]
Well, its alive again :)

Released https://github.com/PipeRift/FactionsExtension/releases/tag/1.9 some days ago, 1.10 coming soon with new features too
