### ISSUE TITLE
Equal / Not Equal may not be working correctly

### ISSUE THREAD

**Issue by DargieDChouwy** [PipeRift/FactionsExtension#3]
**Describe the bug**

> A clear and concise description of what the bug is.

So, I am using **Equal** or **Not Equal** with a **Branch** to make the difference between each factions. But it seem it don't work, it always go to true or false for every players. Like it don't seem to recognize faction's players.

**To Reproduce**

> Steps to reproduce the behavior:

I. Add interface faction for actors and characters
II. Add their faction value in the interfaces
III. Create relation between factions

1. Create a **Box collision on a staticmesh**
2. Create a **On component Begin overlap** of the box collision
3. Link the On component begin overlap event to a branch, set a **print string** for each value. True if it go to true and false if it go to false. 
4. Create a variable of faction, set the type of variable to faction. Chose value to enemy
4. Add **Equal** to the  condition of the branch, set the variable to the value and the second to Enemy.

**Logs**

> It's helps us a lot to have a log. If you can, drop the last one here.
I don't have any log

**[Optional] Screenshots if any**

> If applicable, add screenshots or videos to help explain your problem.

Blueprint for the box collision with the branch and the equal:
http://prntscr.com/m3p9pr

Blueprint for enemy character:
http://prntscr.com/m3p9z0

GetFaction function of the enemy character:
http://prntscr.com/m3pa5n

Blueprint for our character:
http://prntscr.com/m3paba

GetFaction function of our character:
http://prntscr.com/m3pags

Faction settings:
http://prntscr.com/m3pap1

**Environment (please complete the following information):**
 - Engine Version: 4.20.3
 - Plugin Version: 1.7b
 - OS: Windows

**[Optional] Additional context**

> Add any other context about the problem here.

I am creating a king of the hill system. So each player owns a faction. In depend of the relation of the faction have the players, the timer in the king of the hill area increase or decrease.

**Comment by muit** [comment]
Hey, thanks for reporting it :)

Can you make a few simple tests while I read it more carefully?

Can you add an equal node with Enemy on both inputs and check that it returns true?
Can you do the same but with two outputs as Player(Joueur)?

**Comment by muit** [comment]
Okay, maybe, you should check for the actor that is overlaping instead of the variable faction?

![image](https://user-images.githubusercontent.com/3672970/50765621-beeaa380-1276-11e9-98db-3d1326433c81.png)

**Comment by DargieDChouwy** [comment]
> 
> 
> Hey, thanks for reporting it :)
> 
> Can you make a few simple tests while I read it more carefully?
> 
> Can you add an equal node with Enemy on both inputs and check that it returns true?
http://prntscr.com/m44uwf

> Can you do the same but with two outputs as Player(Joueur)?
http://prntscr.com/m44vaa 

Anyways, it return always true or false, it can't do the difference between the values

**Comment by DargieDChouwy** [comment]
> 
> 
> Okay, maybe, you should check for the actor that is overlaping instead of the variable faction?
> 
> ![image](https://user-images.githubusercontent.com/3672970/50765621-beeaa380-1276-11e9-98db-3d1326433c81.png)
> I am not sure what that variable does on the hill, but I assume since you are detecting an overlap, you want to check the actor that overlapped

uhm, so, how I can do the distinction between 2 factions? For example, blue vs red, how my overlap can do know who is the enemy in order to start the countdown ? 
And if there is many faction ?

**Comment by muit** [comment]
mm well, you can get a faction from an actor, in this case from the actor the event gives you.
Also, most times you don't want to compare factions with == but to check their attitude to see if they are enemy, friend or ally

**Comment by DargieDChouwy** [comment]
Ok, thank you
I'll retry another way, should I come back posting the solution?

**Comment by muit** [comment]
mm by actor i mean the Actor class. Character and Pawn are actors

**Comment by muit** [comment]
Since this doesn't look like a bug, I will close it for tracking purposes.

Thanks for posting it, you know where to find me for anything else :)
